### ISSUE TITLE
Image Vulnerabilities Scan Result page: Image tag is truncated

### ISSUE THREAD

**Issue by v1r7u** [deepnetworkgmbh/security-monitor-core#11]
### Security Monitor Version

The docker-image version is `deepnetwork/security-monitor:0.1.1`, which is built from commit `b5516db74c5e0b985656f2aa9d2573aba279e97b`

### Expected Behavior

When `/image/{image-tag}` is opened, the header should contain meaningful image tag.

If the tag is too long - it should be truncated, but this should be highlighted somehow: `...` or use some shortening heuristic.

Also, on mouse-hover the full image tag should be in popup

### Actual Behavior

![image](https://user-images.githubusercontent.com/1583399/70637084-ee4c2200-1c36-11ea-8d66-9315f3a68233.png)

### Steps to Reproduce

Open image scan details for any image with long tag, for example `kube-system` images provided by AKS

**Comment by detaybey** [comment]
![image (1)](https://user-images.githubusercontent.com/784409/70808533-eaec9e00-1dd0-11ea-9b28-281a594446a0.png)
it is better now with the human readable response, but needs a style makeup. After that i'll close this issue.
