### ISSUE TITLE
Create "Container Image Vulnerabilities Scans general overview" page

### ISSUE THREAD

**Issue by v1r7u** [deepnetworkgmbh/security-monitor-core#3]
The single page should display a summary for all used container images in the entire infrastructure:
- how many unique images are running, percent of images with and without issues (charts?)
- collapsible list of all the images ordered by issues severity

List of images should support grouping by namespaces/tags

Data for the view should be queried from `scanners/api/container-images/`. The associated task from scanners repository - [Issue 3](https://github.com/deepnetworkgmbh/security-monitor-scanners/issues/3)

Design proposals: https://wireframe.cc/SlbGtU
![image](https://user-images.githubusercontent.com/1583399/70605524-fa19f300-1bfa-11ea-99f2-0f4debd640b4.png)

**Comment by detaybey** [comment]
![Dec-13-2019 19-17-31](https://user-images.githubusercontent.com/784409/70814936-9a2f7200-1ddd-11ea-9579-ac34b73302dc.gif)
current behavior, work in progress.

**Comment by detaybey** [comment]
<img width="716" alt="Screen Shot 2019-12-17 at 10 59 01" src="https://user-images.githubusercontent.com/784409/70976074-48783780-20bc-11ea-85e1-a1eeaf2637a7.png">
